AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FastAPI Presign Service

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Architectures:
      - x86_64   # or use arm64 if you're building an ARM container

Resources:
  FastAPIFunction:
    Type: AWS::Serverless::Function
    Metadata:
      DockerTag: latest
      DockerContext: .
      Dockerfile: Dockerfile.lambda
    Properties:
      PackageType: Image
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          MOCK_BUCKET_NAME: mock-bucket
          MOCK_REGION: us-east-1

Outputs:
  FastAPIFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt FastAPIFunction.Arn
  FastAPIApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
